### ISSUE TITLE
Fix initialization bugs

### ISSUE THREAD

**Issue by girazoki** [witnet/witnet-rust#1371] opened 2020-07-03 16:02 UTC
Currently master is broken and cannot be initialized. The following issues have been discovered:

A) When the difficulty is high, the last beacon is apparently not set properly with respect to the epoch and stays at 0, hash. This causes that the peers do not sync anymore with their outbounds, as the epoch differs. Potential solutions might be toa ccept beacons that are below your epoch.

B) Race conditions: It hasbeen observed that some times, specially when you specify yourself as outbound, the session manager tries to establish connection before the genesis is created. Since the beacons are not set, this causes the session not to be opened.

C) SetLastBeacon is apparently not set when the genesis is created. This causes that if a network has the genesis conslidated but a new node does not, the new node sees a mismatch between the network beacon (genesis) and his beacon (bootstrap)

D) superblock intiialization fails as it tries to quiery a non-existent chain state

**Comment by tmpolaczyk** [comment] 2020-07-06 07:14
In PR #1370 I try to fix A, C, and D

**Comment by tmpolaczyk** [comment] 2020-07-06 09:56
B was also fixed in #1370 

The race condition may still happen if the feeler starts before the SetLastBeacon message arrives to SessionsManager, but we were not able to reproduce that case, so closing.

**Closed by tmpolaczyk** 2020-07-06 09:56 UTC
Labels: bug 🐜, liveness ⚡️
