### ISSUE TITLE
Error synchronizing the wallet when running it in a local environment

### ISSUE THREAD

**Issue by gabaldon** [witnet/witnet-rust#1761] opened 2020-12-02 13:24 UTC
Opening and closing Sheikah several times and letting the wallet running in a local environment breaks synchronization. While the issue [[Wallet] "Unknown" panic on wallet #1747](https://github.com/witnet/witnet-rust/issues/1747) is solved by [fix(wallet): includes future::lazy in a block_on call #1759](https://github.com/witnet/witnet-rust/pull/1759), the synchronization keeps getting stock in (0.00%...). 

After closing and reopening both the wallet and Sheikah, the wallet starts accepting different tcp connections and Sheikah breaks:

<img width="1274" alt="Captura de pantalla 2020-12-02 a las 13 56 42" src="https://user-images.githubusercontent.com/16032491/100876791-2aac0a00-34a8-11eb-9f4c-9e4af1397bde.png">

```
[2020-12-02T12:52:05Z INFO  witnet_wallet::actors::worker::methods] Superblock #44050 notification received. 
Consolidating 4 pending blocks...
[2020-12-02T12:53:00Z INFO  parity_ws::io] Accepted a new tcp connection from 127.0.0.1:50833.
[2020-12-02T12:53:10Z INFO  witnet_wallet::actors::app::routes] New WS notifications subscriber for session 60459...
[2020-12-02T12:53:10Z INFO  witnet_wallet::actors::worker::methods] [SU] Starting synchronization of wallet 1923e947eefe8524ee3374446a0629cd523492b5f8170d8fef276a10c48416b9.
    	[Local beacon] CheckpointBeacon { checkpoint: 176199, hash_prev_block: 41f54c413928e362d61d9f5e3314f5bc15f876d63b0105dffebad2ab99ea8ae9 }
    	[Node height ]   BlockInfo { checkpoint: 176205, block_hash: 8bd40022aef3f79a6170d7df87892c9421a30ece53726f1ec46093169356cd09 }
[2020-12-02T12:53:11Z INFO  witnet_wallet::actors::worker::methods] [SU] Wallet 1923e947eefe8524ee3374446a0629cd523492b5f8170d8fef276a10c48416b9 is now synced up to latest beacon (CheckpointBeacon { checkpoint: 176205, hash_prev_block: a99adca21e58c993f549d92e700da6f3d85598d7c43ae78f52cdaea91228ff52 })
[2020-12-02T12:54:05Z INFO  witnet_wallet::actors::worker::methods] Superblock #44051 notification received. Consolidating 4 pending blocks...
[2020-12-02T12:54:39Z INFO  parity_ws::io] Accepted a new tcp connection from 127.0.0.1:50850.
[2020-12-02T12:55:36Z INFO  parity_ws::io] Accepted a new tcp connection from 127.0.0.1:50867.
[2020-12-02T12:56:06Z INFO  parity_ws::io] Accepted a new tcp connection from 127.0.0.1:50879.
```

**Comment by tmpolaczyk** [comment] 2020-12-02 13:57
I can reproduce this using sheikah on https://github.com/witnet/sheikah/commit/e3385e1903a9ca70b4dd80e368cd28f0a24754f0, and it may be because after closing sheikah it keeps running in the background.

Steps to reproduce:

1. Compile sheikah:

`yarn electron:build`

2. Run sheikah:

`./dist_electron/Sheikah\ Witnet\ wallet-1.5.1.AppImage --no-sandbox`

3. Wait until the login screen in sheikah, but don't unlock any wallet.
4. Close sheikah using alt+f4 or equivalent
5. Check if sheikah is still running:

`ps aux | grep Sheikah`

6. If sheikah is not running, open sheikah again. I had to retry it 3 times.

So even after closing sheikah, there is a sheikah process running, as well as a wallet process. The old sheikah process connects to the wallet. Not sure why would this break the wallet, but I think this is the issue.

**Comment by tmpolaczyk** [comment] 2020-12-03 10:54
See the attached backtrace: it looks like the wallet gets stuck while waiting for the write lock in the `update_sync_state` method:

[maria-bt-all.txt](https://github.com/witnet/witnet-rust/files/5635554/maria-bt-all.txt)

**Closed** 2020-12-04 15:53 UTC
